name: Build and Push Docker image
on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - '**.yml'
      - 'LICENSE'
  workflow_dispatch:

env:
  IMAGE_NAME: "loadtest-test-api"
  DOCKER_FILE_PATH: "./GoLang/deployments/dockerfile"
  DOCKER_USERNAME: jake4

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: BBuild and Push Docker Image for loadtest-test-api
        uses: docker/build-push-action@v4
        with:
          context: ./GoLang
          file: ${{ env.DOCKER_FILE_PATH }}
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}